### ISSUE TITLE
JumpPads Bug / AntiMultiAura Bug / Kick Bug

### ISSUE THREAD

**Issue by DrTripple** [CCBlueX/AdvanceNoCheat-Issues#1]
1. Wenn ich den JumpPads nutzen will muss ich Fly/Speed/YAxis ausstellen wie kann ich das ändern?
2.Dein AntiCheat Plugin klappt mit den PvP System von 1.9 Nicht wenn man mehrer Mobs gleichzeit schlagen kann mit dem Schwingen vom Schwert. Dann bekomme ich als Admin eine Nachricht das Er MultiAura an hat
3. Wenn man ein Tier killt wird man gekickt vom Server

**Comment by Marco-MC** [comment]
Danke, für dein Bug Report. Wir werden uns um die Fehler kümmern.
Wegen dem Fehler das man gekickt wird hätten wird bitte einmal gerne den Konsolen Log und den KickScreen.

**Comment by Marco-MC** [comment]
Und wegen den JumpPads. Wir werden es fixen das man die JumpPads auch ohne deaktivieren von Fly/Speed/YAxis nutzen kann.

**Comment by DrTripple** [comment]
http://img5.fotos-hochladen.net/uploads/aacabimor7pzg.png - Kick Message
Den Log kann ich grade leider nicht schicken da der Root in Update-Phase ist und nicht zugreifen kann.

**Comment by Marco-MC** [comment]
Das ist komisch. Hast du andere Plugins auf dem Server? Vielleicht ist da etwas nicht kompatibel.

**Comment by Marco-MC** [comment]
Ich habe den Fehler jetz auch. Ich kann ihn also jetz fixen.
