### ISSUE TITLE
1.10.2服务器  AdvanceNoCheatV2.3

### ISSUE THREAD

**Issue by huazhizhaozhan** [CCBlueX/AdvanceNoCheat-Issues#10]
27.08 15:08:31 [Server] INFO Hikai failed NoSwing/AntiNoSwing: {subInformations}
27.08 15:08:31 [Server] INFO Hikai failed NoSwing/AntiNoSwing: {subInformations}
27.08 15:08:31 [Server] INFO Hikai failed NoSwing/AntiNoSwing: {subInformations}

**Comment by Marco-MC** [comment]
What is here the bug?
