### ISSUE TITLE
v2.5 takes too much CPU

### ISSUE THREAD

**Issue by nozombieWK** [CCBlueX/AdvanceNoCheat-Issues#15]
I used NCP until I saw this plugin.It's not as good as yours.I tested this plugin on my PC, but when I install it in my server, the plugin takes a lot and lots of CPU even if there's no one playing.Would you mind fixing this?Thanks!
OS: Windows Server 2012 r2 Datacenter (Chinese)
Java: Jre8
Bukkit: PaperSpigot 1.8.8 with plugin "ProtocolSupport"

**Comment by Marco-MC** [comment]
You can disable AntiESP. AntiESP attracts a lot of CPU.
