### ISSUE TITLE
Couldn't pass move event

### ISSUE THREAD

**Issue by crzassassin** [CCBlueX/AdvanceNoCheat-Issues#6]
23.08 13:09:03 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot1.8.jar:git-Spigot-dbe012b-61ef214]
23.08 13:09:03 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot1.8.jar:git-Spigot-dbe012b-61ef214]
23.08 13:09:03 [Server] INFO org.bukkit.event.EventException
23.08 13:09:03 [Server] ERROR Could not pass event PlayerMoveEvent to AdvanceNoCheat v2.1
23.08 13:09:03 [Server] INFO ... 15 more
23.08 13:09:03 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot1.8.jar:git-Spigot-dbe012b-61ef214]
23.08 13:09:03 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
23.08 13:09:03 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
23.08 13:09:03 [Server] INFO at sun.reflect.GeneratedMethodAccessor166.invoke(Unknown Source) ~[?:?]
23.08 13:09:03 [Server] INFO at _AdvanceNoCheat__OBFUSCATION_______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________5358652192975182926_._AdvanceNoCheat__OBFUSCATION_______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________9142990648623780471_(AntiKillAura.java:131) ~[?:?]
23.08 13:09:03 [Server] INFO at _AdvanceNoCheat__OBFUSCATION_______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________310361268742204067_._AdvanceNoCheat__OBFUSCATION_______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________5172880757792094780_(Module.java:62) ~[?:?]
23.08 13:09:03 [Server] INFO Caused by: java.lang.NullPointerException
23.08 13:09:03 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
23.08 13:09:03 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot1.8.jar:git-Spigot-dbe012b-61ef214]
23.08 13:09:03 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot1.8.jar:git-Spigot-dbe012b-61ef214]
23.08 13:09:03 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot1.8.jar:git-Spigot-dbe012b-61ef214]
23.08 13:09:03 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot1.8.jar:git-Spigot-dbe012b-61ef214]
23.08 13:09:03 [Server] INFO at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot1.8.jar:git-Spigot-dbe012b-61ef214]
23.08 13:09:03 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_77]
23.08 13:09:03 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_77]
23.08 13:09:03 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot1.8.jar:git-Spigot-dbe012b-61ef214]
23.08 13:09:03 [Server] INFO at net.minecraft.server.v1_8_R2.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot1.8.jar:git-Spigot-dbe012b-61ef214]
23.08 13:09:03 [Server] INFO at net.minecraft.server.v1_8_R2.PacketPlayInFlying.a(SourceFile:126) [spigot1.8.jar:git-Spigot-dbe012b-61ef214]
23.08 13:09:03 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:265) [spigot1.8.jar:git-Spigot-dbe012b-61ef214]
23.08 13:09:03 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot1.8.jar:git-Spigot-dbe012b-61ef214]
23.08 13:09:03 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot1.8.jar:git-Spigot-dbe012b-61ef214]
23.08 13:09:03 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot1.8.jar:git-Spigot-dbe012b-61ef214]
23.08 13:09:03 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot1.8.jar:git-Spigot-dbe012b-61ef214]
23.08 13:09:03 [Server] INFO org.bukkit.event.EventException
23.08 13:09:03 [Server] ERROR Could not pass event PlayerMoveEvent to AdvanceNoCheat v2.1

**Comment by Marco-MC** [comment]
Okay. Thanks for the bug Report. :)
