### ISSUE TITLE
错误报告

### ISSUE THREAD

**Issue by huazhizhaozhan** [CCBlueX/AdvanceNoCheat-Issues#8]
at org.bukkit.Location.distanceSquared(Location.java:456) ~[patched_1.10.2.jar:git-Paper-842]
27.08 13:25:50 [Server] INFO Caused by: java.lang.IllegalArgumentException: Cannot measure distance between world and Yongzhou
27.08 13:25:50 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
27.08 13:25:50 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624) [patched_1.10.2.jar:git-Paper-842]
27.08 13:25:50 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725) [patched_1.10.2.jar:git-Paper-842]
27.08 13:25:50 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-842]
27.08 13:25:50 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:791) [patched_1.10.2.jar:git-Paper-842]
27.08 13:25:50 [Server] INFO at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [patched_1.10.2.jar:git-Paper-842]
27.08 13:25:50 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
27.08 13:25:50 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
27.08 13:25:50 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.10.2.jar:git-Paper-842]
27.08 13:25:50 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [patched_1.10.2.jar:git-Paper-842]
27.08 13:25:50 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInFlying.a(SourceFile:126) [patched_1.10.2.jar:git-Paper-842]
27.08 13:25:50 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:611) [patched_1.10.2.jar:git-Paper-842]
27.08 13:25:50 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.10.2.jar:git-Paper-842]
27.08 13:25:50 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.10.2.jar:git-Paper-842]
27.08 13:25:50 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [patched_1.10.2.jar:git-Paper-842]
27.08 13:25:50 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) [patched_1.10.2.jar:git-Paper-842]
27.08 13:25:50 [Server] INFO at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) [patched_1.10.2.jar:git-Paper-842]
27.08 13:25:50 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor336.execute(Unknown Source) [?:?]
27.08 13:25:50 [Server] INFO at tk.ccbluex.AdvanceNoCheat.event.EventManager.onMove(EventManager.java:53) [反作弊—AdvanceNoCheat%20v2.3.jar:?]
27.08 13:25:50 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.10.2.jar:git-Paper-842]
27.08 13:25:50 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.10.2.jar:git-Paper-842]
27.08 13:25:50 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.10.2.jar:git-Paper-842]
27.08 13:25:50 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.10.2.jar:git-Paper-842]
27.08 13:25:50 [Server] INFO at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.10.2.jar:git-Paper-842]
27.08 13:25:50 [Server] INFO org.bukkit.event.EventException
27.08 13:25:50 [Server] ERROR Could not pass event _AdvanceNoCheat__OBFUSCATION_______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________1146838445225797217_ to AdvanceNoCheat v2.3

**Comment by Marco-MC** [comment]
We fix this error soon. :)
